/**
 * Script to extract Firebase credentials from Service Account JSON and write to .env
 *
 * Usage: npx ts-node scripts/load-firebase-env.ts <path-to-service-account-json>
 *
 * Example: npx ts-node scripts/load-firebase-env.ts ../api-web-agencia-firebase-admin.json
 */

import * as fs from 'fs';
import * as path from 'path';

interface ServiceAccount {
  project_id: string;
  client_email: string;
  private_key: string;
}

function loadFirebaseEnv(jsonPath: string): void {
  // Resolve absolute path
  const absolutePath = path.resolve(jsonPath);

  if (!fs.existsSync(absolutePath)) {
    console.error(`Error: File not found: ${absolutePath}`);
    process.exit(1);
  }

  let serviceAccount: ServiceAccount;
  try {
    const content = fs.readFileSync(absolutePath, 'utf-8');
    serviceAccount = JSON.parse(content);
  } catch (error) {
    console.error(`Error: Invalid JSON file: ${absolutePath}`);
    process.exit(1);
  }

  // Validate required fields
  if (!serviceAccount.project_id || !serviceAccount.client_email || !serviceAccount.private_key) {
    console.error('Error: JSON file missing required fields (project_id, client_email, private_key)');
    process.exit(1);
  }

  // Escape newlines in private key for .env format
  const escapedPrivateKey = serviceAccount.private_key.replace(/\n/g, '\\n');

  // Read existing .env or create new one
  const envPath = path.resolve(process.cwd(), '.env');
  let envContent = '';

  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, 'utf-8');
  }

  // Remove existing Firebase entries if present
  envContent = envContent
    .split('\n')
    .filter(line => !line.startsWith('FIREBASE_'))
    .join('\n')
    .trim();

  // Append new Firebase configuration
  const firebaseVars = `
# -----------------------------------------------------------------------------
# Firebase Admin SDK (Generated by scripts/load-firebase-env.ts)
# -----------------------------------------------------------------------------
FIREBASE_PROJECT_ID=${serviceAccount.project_id}
FIREBASE_CLIENT_EMAIL=${serviceAccount.client_email}
FIREBASE_PRIVATE_KEY="${escapedPrivateKey}"
`.trim();

  envContent = envContent + '\n' + firebaseVars + '\n';

  fs.writeFileSync(envPath, envContent, 'utf-8');

  console.log('Firebase environment variables written to .env');
  console.log(`  FIREBASE_PROJECT_ID=${serviceAccount.project_id}`);
  console.log(`  FIREBASE_CLIENT_EMAIL=${serviceAccount.client_email}`);
}

const jsonPath = process.argv[2];

if (!jsonPath) {
  console.error('Usage: npx ts-node scripts/load-firebase-env.ts <path-to-service-account-json>');
  process.exit(1);
}

loadFirebaseEnv(jsonPath);